# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/elwaseet_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_DB_PASSWORD_HERE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true

# JWT Configuration
jwt.secret=JWT_SECRET_KEY_HERE
jwt.expiration=604800000

# Server Port
server.port=8080

# Email config
resend.test.to=EMAIL_TEST_ADDRESS_HERE
resend.api.key=RESEND_API_KEY_HERE
resend.from=onboarding@resend.dev
