export const MOCK_USERS = {
    customer: {
        id: 'cust-001',
        email: 'customer@test.com',
        password: 'Test123!',
        fullName: 'John Customer',
        phone: '+9611234567',
        location: 'Beirut',
        role: 'customer',
        isVerified: true,
        createdAt: '2024-01-15T10:00:00Z',
    },
    provider: {
        id: 'prov-001',
        email: 'provider@test.com',
        password: 'Test123!',
        fullName: 'Sarah Provider',
        phone: '+9611234568',
        location: 'Beirut',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-01-15T10:00:00Z',
        services: ['Plumbing', 'Electrical'],
        hourlyRate: 50,
        rating: 4.8,
        reviewCount: 24,
        bio: 'Experienced plumber and electrician with 10+ years of experience',
    },
    hybrid: {
        id: 'hyb-001',
        email: 'hybrid@test.com',
        password: 'Test123!',
        fullName: 'Mike Hybrid',
        phone: '+9611234569',
        location: 'Beirut',
        role: 'hybrid',
        isVerified: true,
        createdAt: '2024-01-15T10:00:00Z',
        services: ['Cleaning', 'Handyman'],
        hourlyRate: 40,
        rating: 4.5,
        reviewCount: 18,
        bio: 'Professional cleaner and handyman',
    },
    admin: {
        id: 'admin-001',
        email: 'admin@test.com',
        password: 'Test123!',
        fullName: 'Admin User',
        phone: '+9611234570',
        location: 'Beirut',
        role: 'admin',
        isVerified: true,
        createdAt: '2024-01-15T10:00:00Z',
    },
    provider2: {
        id: 'prov-002',
        email: 'provider2@test.com',
        password: 'Test123!',
        fullName: 'Ahmed Electrician',
        phone: '+9611234571',
        location: 'Tripoli',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-02-10T10:00:00Z',
        services: ['Electrical', 'AC Repair'],
        hourlyRate: 45,
        rating: 4.9,
        reviewCount: 32,
        bio: 'Certified electrician specializing in residential and commercial electrical work',
    },
    provider3: {
        id: 'prov-003',
        email: 'provider3@test.com',
        password: 'Test123!',
        fullName: 'Maria Cleaner',
        phone: '+9611234572',
        location: 'Beirut',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-03-05T10:00:00Z',
        services: ['Cleaning', 'Laundry'],
        hourlyRate: 35,
        rating: 4.7,
        reviewCount: 45,
        bio: 'Professional cleaning service with eco-friendly products',
    },
    provider4: {
        id: 'prov-004',
        email: 'provider4@test.com',
        password: 'Test123!',
        fullName: 'Hassan Carpenter',
        phone: '+9611234573',
        location: 'Sidon',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-04-12T10:00:00Z',
        services: ['Carpentry', 'Furniture Assembly'],
        hourlyRate: 55,
        rating: 4.6,
        reviewCount: 28,
        bio: 'Expert carpenter with 15 years of experience in custom furniture',
    },
    provider5: {
        id: 'prov-005',
        email: 'provider5@test.com',
        password: 'Test123!',
        fullName: 'Layla Painter',
        phone: '+9611234574',
        location: 'Beirut',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-05-20T10:00:00Z',
        services: ['Painting', 'Wallpaper'],
        hourlyRate: 40,
        rating: 4.8,
        reviewCount: 36,
        bio: 'Professional painter specializing in interior and exterior painting',
    },
    provider6: {
        id: 'prov-006',
        email: 'provider6@test.com',
        password: 'Test123!',
        fullName: 'Omar Gardener',
        phone: '+9611234575',
        location: 'Jounieh',
        role: 'provider',
        isVerified: true,
        createdAt: '2024-06-15T10:00:00Z',
        services: ['Gardening', 'Landscaping'],
        hourlyRate: 38,
        rating: 4.5,
        reviewCount: 22,
        bio: 'Experienced gardener and landscaping specialist',
    },
    customer2: {
        id: 'cust-002',
        email: 'customer2@test.com',
        password: 'Test123!',
        fullName: 'Lisa Johnson',
        phone: '+9611234576',
        location: 'Tripoli',
        role: 'customer',
        isVerified: true,
        createdAt: '2024-02-20T10:00:00Z',
    },
    customer3: {
        id: 'cust-003',
        email: 'customer3@test.com',
        password: 'Test123!',
        fullName: 'David Martinez',
        phone: '+9611234577',
        location: 'Sidon',
        role: 'customer',
        isVerified: true,
        createdAt: '2024-03-15T10:00:00Z',
    },
};

export const MOCK_JOBS = [{
        id: 'job-001',
        title: 'Fix leaking kitchen sink',
        description: 'Kitchen sink has been leaking for a week. Need urgent repair.',
        category: 'Plumbing',
        location: 'Beirut',
        budgetMin: 50,
        budgetMax: 100,
        photos: [],
        status: 'OPEN',
        customerId: 'cust-001',
        providerId: null,
        createdAt: '2024-12-01T10:00:00Z',
    },
    {
        id: 'job-002',
        title: 'House cleaning service',
        description: 'Need deep cleaning for 3-bedroom apartment',
        category: 'Cleaning',
        location: 'Beirut',
        budgetMin: 80,
        budgetMax: 150,
        photos: [],
        status: 'IN_PROGRESS',
        customerId: 'cust-001',
        providerId: 'prov-001',
        createdAt: '2024-11-28T10:00:00Z',
    },
    {
        id: 'job-003',
        title: 'Install ceiling fan',
        description: 'Need electrician to install new ceiling fan in bedroom',
        category: 'Electrical',
        location: 'Beirut',
        budgetMin: 60,
        budgetMax: 120,
        photos: [],
        status: 'COMPLETED',
        customerId: 'cust-001',
        providerId: 'prov-001',
        createdAt: '2024-11-25T10:00:00Z',
    },
    {
        id: 'job-004',
        title: 'Paint living room',
        description: 'Looking for painter to paint living room walls',
        category: 'Painting',
        location: 'Beirut',
        budgetMin: 200,
        budgetMax: 350,
        photos: [],
        status: 'OPEN',
        customerId: 'hyb-001',
        providerId: null,
        createdAt: '2024-12-02T08:00:00Z',
    },
    {
        id: 'job-005',
        title: 'AC maintenance and cleaning',
        description: 'Need AC technician for annual maintenance and cleaning of 3 units',
        category: 'AC Repair',
        location: 'Tripoli',
        budgetMin: 100,
        budgetMax: 180,
        photos: [],
        status: 'OPEN',
        customerId: 'cust-002',
        providerId: null,
        createdAt: '2024-12-03T09:00:00Z',
    },
    {
        id: 'job-006',
        title: 'Build custom bookshelf',
        description: 'Need carpenter to build a custom bookshelf for home office',
        category: 'Carpentry',
        location: 'Sidon',
        budgetMin: 300,
        budgetMax: 500,
        photos: [],
        status: 'OPEN',
        customerId: 'cust-003',
        providerId: null,
        createdAt: '2024-12-03T11:00:00Z',
    },
    {
        id: 'job-007',
        title: 'Garden landscaping',
        description: 'Transform backyard garden with new plants and design',
        category: 'Gardening',
        location: 'Jounieh',
        budgetMin: 400,
        budgetMax: 700,
        photos: [],
        status: 'IN_PROGRESS',
        customerId: 'cust-002',
        providerId: 'prov-006',
        createdAt: '2024-11-30T10:00:00Z',
    },
    {
        id: 'job-008',
        title: 'Weekly house cleaning',
        description: 'Looking for reliable cleaner for weekly house cleaning service',
        category: 'Cleaning',
        location: 'Beirut',
        budgetMin: 60,
        budgetMax: 100,
        photos: [],
        status: 'OPEN',
        customerId: 'cust-003',
        providerId: null,
        createdAt: '2024-12-04T08:00:00Z',
    },
    {
        id: 'job-009',
        title: 'Bathroom renovation painting',
        description: 'Need painter for bathroom walls after renovation',
        category: 'Painting',
        location: 'Beirut',
        budgetMin: 120,
        budgetMax: 200,
        photos: [],
        status: 'PENDING',
        customerId: 'cust-001',
        providerId: null,
        createdAt: '2024-12-04T10:00:00Z',
    },
    {
        id: 'job-010',
        title: 'Fix electrical outlet',
        description: 'One electrical outlet not working in living room',
        category: 'Electrical',
        location: 'Tripoli',
        budgetMin: 40,
        budgetMax: 80,
        photos: [],
        status: 'CONFIRMED',
        customerId: 'cust-002',
        providerId: 'prov-002',
        createdAt: '2024-11-27T10:00:00Z',
    },
];

export const MOCK_APPLICATIONS = [{
        id: 'app-001',
        jobId: 'job-001',
        providerId: 'prov-001',
        quote: 75,
        availability: 'Available today',
        message: 'I can fix this quickly. I have 10 years of plumbing experience.',
        status: 'PENDING',
        createdAt: '2024-12-01T11:00:00Z',
    },
    {
        id: 'app-002',
        jobId: 'job-004',
        providerId: 'prov-005',
        quote: 280,
        availability: 'Available this weekend',
        message: 'Professional painting service with quality materials.',
        status: 'PENDING',
        createdAt: '2024-12-02T09:00:00Z',
    },
    {
        id: 'app-003',
        jobId: 'job-001',
        providerId: 'hyb-001',
        quote: 85,
        availability: 'Available tomorrow',
        message: 'I can help with plumbing repairs. Quick and reliable service.',
        status: 'PENDING',
        createdAt: '2024-12-01T14:00:00Z',
    },
    {
        id: 'app-004',
        jobId: 'job-005',
        providerId: 'prov-002',
        quote: 150,
        availability: 'Available this week',
        message: 'Certified AC technician with 8 years experience. Will clean and maintain all units.',
        status: 'PENDING',
        createdAt: '2024-12-03T10:00:00Z',
    },
    {
        id: 'app-005',
        jobId: 'job-006',
        providerId: 'prov-004',
        quote: 420,
        availability: 'Can start next week',
        message: 'Expert carpenter. I will build a custom bookshelf exactly to your specifications.',
        status: 'PENDING',
        createdAt: '2024-12-03T12:00:00Z',
    },
    {
        id: 'app-006',
        jobId: 'job-008',
        providerId: 'prov-003',
        quote: 80,
        availability: 'Available every Friday',
        message: 'Professional cleaning service. I use eco-friendly products and have excellent references.',
        status: 'PENDING',
        createdAt: '2024-12-04T09:00:00Z',
    },
    {
        id: 'app-007',
        jobId: 'job-008',
        providerId: 'hyb-001',
        quote: 70,
        availability: 'Flexible schedule',
        message: 'Reliable weekly cleaning service. I have been doing this for 5 years.',
        status: 'PENDING',
        createdAt: '2024-12-04T11:00:00Z',
    },
    {
        id: 'app-008',
        jobId: 'job-009',
        providerId: 'prov-005',
        quote: 160,
        availability: 'Available this weekend',
        message: 'Specialized in bathroom painting. Will ensure waterproof finish.',
        status: 'ACCEPTED',
        createdAt: '2024-12-04T11:30:00Z',
    },
    {
        id: 'app-009',
        jobId: 'job-004',
        providerId: 'hyb-001',
        quote: 250,
        availability: 'Available next week',
        message: 'I can paint your living room with premium quality paint.',
        status: 'REJECTED',
        createdAt: '2024-12-02T15:00:00Z',
    },
];

export const MOCK_NOTIFICATIONS = [{
        id: 'notif-001',
        userId: 'cust-001',
        type: 'APPLICATION_RECEIVED',
        message: 'You received a new application for "Fix leaking kitchen sink"',
        isRead: false,
        createdAt: '2024-12-01T11:00:00Z',
    },
    {
        id: 'notif-002',
        userId: 'prov-001',
        type: 'APPLICATION_ACCEPTED',
        message: 'Your application for "House cleaning service" was accepted',
        isRead: true,
        createdAt: '2024-11-28T12:00:00Z',
    },
    {
        id: 'notif-003',
        userId: 'cust-001',
        type: 'APPLICATION_RECEIVED',
        message: 'You received a new application for "Fix leaking kitchen sink"',
        isRead: false,
        createdAt: '2024-12-01T14:00:00Z',
    },
    {
        id: 'notif-004',
        userId: 'hyb-001',
        type: 'APPLICATION_RECEIVED',
        message: 'You received a new application for "Paint living room"',
        isRead: false,
        createdAt: '2024-12-02T09:00:00Z',
    },
    {
        id: 'notif-005',
        userId: 'prov-005',
        type: 'APPLICATION_ACCEPTED',
        message: 'Your application for "Bathroom renovation painting" was accepted',
        isRead: false,
        createdAt: '2024-12-04T11:30:00Z',
    },
    {
        id: 'notif-006',
        userId: 'hyb-001',
        type: 'APPLICATION_REJECTED',
        message: 'Your application for "Paint living room" was rejected',
        isRead: true,
        createdAt: '2024-12-02T16:00:00Z',
    },
    {
        id: 'notif-007',
        userId: 'cust-002',
        type: 'JOB_COMPLETED',
        message: 'Job "Fix electrical outlet" has been marked as completed',
        isRead: false,
        createdAt: '2024-12-03T15:00:00Z',
    },
    {
        id: 'notif-008',
        userId: 'prov-006',
        type: 'JOB_STARTED',
        message: 'You can now start working on "Garden landscaping"',
        isRead: true,
        createdAt: '2024-11-30T11:00:00Z',
    },
];

// Mock API delay
export const mockDelay = (ms = 500) => new Promise(resolve => setTimeout(resolve, ms));

// Mock authentication
export const mockLogin = async (email, password) => {
    await mockDelay();

    const user = Object.values(MOCK_USERS).find(
        u => u.email === email && u.password === password
    );

    if (!user) {
        throw new Error('Invalid email or password');
    }

    const token = 'mock-jwt-token-' + user.id;
    return {
        token,
        user
    };
};

// Mock OTP verification
export const mockVerifyOTP = async (email, otp) => {
    await mockDelay();

    // Accept any 6-digit OTP for testing
    if (otp.length !== 6) {
        throw new Error('Invalid OTP');
    }

    let user = Object.values(MOCK_USERS).find(u => u.email === email);
    
    // FALLBACK: If user not found (mock data reset), create on the fly to unblock testing
    if (!user) {
        // throw new Error('User not found'); 
        console.warn('Mock User not found for verification, creating fallback user');
        user = {
            id: 'fallback-' + Date.now(),
            email: email,
            fullName: 'Test User',
            role: 'customer', // Default role
            isVerified: true,
            createdAt: new Date().toISOString()
        };
    } else {
        user.isVerified = true;
    }

    const token = 'mock-jwt-token-' + user.id;
    return {
        token,
        user
    };
};